In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
# Base directory
path = r"dataset/synthetic_dataset/synthetic_mobile_money_transaction_dataset.csv"

df = pd.read_csv(path)
print("Shape : " , df.shape)
df.head()

Shape :  (1720181, 10)

,step,transactionType,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud
0,0,TRANSFER,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1
1,0,PAYMENT,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0
2,0,PAYMENT,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0
3,0,TRANSFER,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1
4,0,PAYMENT,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0

In [3]:
# # Base directory
# path = "dataset/synthetic_dataset/MoMTSim_20240722202413_1000_dataset.csv"

# df = pd.read_csv(path)
# print("Shape : " , df.shape)
# df.head()

In [3]:
df_clean = df.copy()

df_clean["index"] = np.arange(len(df))

df_clean.info()
df_clean.describe(include="all").T

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1720181 entries, 0 to 1720180
Data columns (total 11 columns):
 #   Column           Dtype
---  ------           -----
 0   step             int64
 1   transactionType  object
 2   amount           float64
 3   initiator        int64
 4   oldBalInitiator  float64
 5   newBalInitiator  float64
 6   recipient        object
 7   oldBalRecipient  float64
 8   newBalRecipient  float64
 9   isFraud          int64
 10  index            int64
dtypes: float64(5), int64(4), object(2)
memory usage: 144.4+ MB

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
step,1720181.0,NaN,NaN,NaN,65.555286,44.673684,0.0,23.0,54.0,106.0,143.0
transactionType,1720181,5,PAYMENT,667245,NaN,NaN,NaN,NaN,NaN,NaN,NaN
amount,1720181.0,NaN,NaN,NaN,52538.679612,88356.497983,0.24,606.46,17298.25,71161.49,2142928.28
initiator,1720181.0,NaN,NaN,NaN,4499951976758673.0,289635131225563.0,4000061963235266.0,4248761574606837.0,4508521162599660.0,4750928280020948.0,4999855045426980.0
oldBalInitiator,1720181.0,NaN,NaN,NaN,2433757.597989,1307614.874018,-199997.11,1577186.32,2619827.17,3361338.4,12244691.62
newBalInitiator,1720181.0,NaN,NaN,NaN,2443879.729006,1297180.529754,-199997.11,1600495.69,2625680.49,3361871.54,12244691.62
recipient,1720181,16731,56-0008969,400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
oldBalRecipient,1720181.0,NaN,NaN,NaN,108508.328753,283013.771027,-198368.47,16064.23,63130.18,137382.17,11885539.37
newBalRecipient,1720181.0,NaN,NaN,NaN,122277.215395,319227.67989,-135727.98,24962.33,74481.61,143170.24,12066212.12
isFraud,1720181.0,NaN,NaN,NaN,0.102035,0.302694,0.0,0.0,0.0,0.0,1.0
index,1720181.0,NaN,NaN,NaN,860090.0,496573.626039,0.0,430045.0,860090.0,1290135.0,1720180.0

In [4]:
"transactionType" in df_clean.columns

True

In [5]:
df_clean.head()

,step,transactionType,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index
0,0,TRANSFER,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0
1,0,PAYMENT,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1
2,0,PAYMENT,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2
3,0,TRANSFER,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3
4,0,PAYMENT,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4

In [6]:
df_clean = pd.get_dummies(df_clean , columns=["transactionType"] , drop_first=False)
df_clean.head()

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,transactionType_DEBIT,transactionType_DEPOSIT,transactionType_PAYMENT,transactionType_TRANSFER,transactionType_WITHDRAWAL
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,False,False,False,True,False
1,0,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1,False,False,True,False,False
2,0,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2,False,False,True,False,False
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,False,False,False,True,False
4,0,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4,False,False,True,False,False

In [7]:
df_clean["amount_balance_ratio"] = df_clean["amount"] / (df_clean["oldBalInitiator"] + 1)
df_clean[["amount" , "oldBalInitiator" , "amount_balance_ratio" , "isFraud"]].head()

     amount  oldBalInitiator  amount_balance_ratio  isFraud
0  19824.96        187712.18              0.105613        1
1    598.97             8.92             60.380040        0
2    545.85            93.60              5.770085        0
3  19847.01          -452.25            -43.982294        1
4    546.89        159148.76              0.003436        0

In [8]:
df_clean["balance_increase_ratio"] = df_clean["amount"] / (df_clean["oldBalRecipient"] + 1e-5)
df_clean[["amount" , "oldBalRecipient" , "balance_increase_ratio" , "isFraud"]].head()

     amount  oldBalRecipient  balance_increase_ratio  isFraud
0  19824.96             8.31            2.385672e+03        1
1    598.97             0.00            5.989700e+07        0
2    545.85             0.00            5.458500e+07        0
3  19847.01          4011.72            4.947257e+00        1
4    546.89             0.00            5.468900e+07        0

In [9]:
df_clean["neg_balance_i"] = (
    (df_clean["oldBalInitiator"] < 0) &
    (df_clean["newBalInitiator"] < 0)
).astype(int)

df_clean.head()

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,transactionType_DEBIT,transactionType_DEPOSIT,transactionType_PAYMENT,transactionType_TRANSFER,transactionType_WITHDRAWAL,amount_balance_ratio,balance_increase_ratio,neg_balance_i
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,False,False,False,True,False,0.105613,2.385672e+03,0
1,0,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1,False,False,True,False,False,60.380040,5.989700e+07,0
2,0,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2,False,False,True,False,False,5.770085,5.458500e+07,0
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,False,False,False,True,False,-43.982294,4.947257e+00,1
4,0,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4,False,False,True,False,False,0.003436,5.468900e+07,0

In [10]:
df_clean["balance_error_i"] = df_clean["newBalInitiator"] - (df_clean["oldBalInitiator"] - df_clean["amount"])

df_clean["balance_error_r"] = df_clean["newBalRecipient"] - (df_clean["oldBalRecipient"] + df_clean["amount"])

df_clean[["balance_error_i" , "balance_error_r"]].head()

   balance_error_i  balance_error_r
0             0.00             0.00
1           598.97          -598.97
2             0.00             0.00
3             0.00             0.01
4             0.01             0.00

In [ ]:
# def add_customer_behavior_features(df, windows=[6, 12, 24]):
    
#     df = df.sort_values(["step", "index"]).copy()
    
#     result_list = []

#     for customer_id, group in df.groupby("initiator"):
        
#         group = group.copy()
        
#         for window in windows:
            
#             # Row-based rolling (last N transactions)
#             group[f"INIT_TX_COUNT_{window}"] = (
#                 group["amount"].rolling(window, min_periods=1).count()
#             )
            
#             group[f"INIT_AVG_AMOUNT_{window}"] = (
#                 group["amount"].rolling(window, min_periods=1).mean()
#             )
            
#             group[f"INIT_SUM_AMOUNT_{window}"] = (
#                 group["amount"].rolling(window, min_periods=1).sum()
#             )
        
#         result_list.append(group)

#     df = pd.concat(result_list)
#     df = df.sort_values(["step", "index"]).reset_index(drop=True)
    
#     return df

# df_clean = add_customer_behavior_features(df_clean)

In [11]:
def add_customer_behavior_features(df, tx_windows=[6, 12, 24], step_windows=[6, 12, 24]):
    
    df = df.sort_values(["initiator", "step", "index"]).copy()
    
    result_list = []

    for customer_id, group in df.groupby("initiator"):
        
        group = group.copy()
        
        # Row-based rolling (last N transactions)
        for window in tx_windows:
            
            group[f"INIT_AVG_AMOUNT_TX_{window}"] = (
                group["amount"].rolling(window, min_periods=1).mean()
            )
            
            # Deviation from rolling average
            group[f"INIT_AMOUNT_DEV_TX_{window}"] = (
                group["amount"] - group[f"INIT_AVG_AMOUNT_TX_{window}"]
            )
        
        # Step-based rolling (last N steps)
        for window in step_windows:
            
            counts = []
            
            steps = group["step"].values
            
            for i in range(len(group)):
                current_step = steps[i]
                
                # Count transactions within [current_step - window, current_step]
                count = ((steps >= current_step - window) & (steps <= current_step)).sum()
                counts.append(count)
            
            group[f"INIT_TX_COUNT_STEP_{window}"] = counts
        
        result_list.append(group)

    df = pd.concat(result_list)
    df = df.sort_values(["step", "index"]).reset_index(drop=True)
    
    return df


df_clean = add_customer_behavior_features(df_clean)
df_clean.head()

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,...,balance_error_r,INIT_AVG_AMOUNT_TX_6,INIT_AMOUNT_DEV_TX_6,INIT_AVG_AMOUNT_TX_12,INIT_AMOUNT_DEV_TX_12,INIT_AVG_AMOUNT_TX_24,INIT_AMOUNT_DEV_TX_24,INIT_TX_COUNT_STEP_6,INIT_TX_COUNT_STEP_12,INIT_TX_COUNT_STEP_24
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,...,0.00,19824.96,0.00,19824.96,0.00,19824.96,0.00,1,1,1
1,0,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1,...,-598.97,598.97,0.00,598.97,0.00,598.97,0.00,1,1,1
2,0,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2,...,0.00,545.85,0.00,545.85,0.00,545.85,0.00,2,2,2
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,...,0.01,10196.43,9650.58,10196.43,9650.58,10196.43,9650.58,2,2,2
4,0,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4,...,0.00,546.89,0.00,546.89,0.00,546.89,0.00,4,4,4

In [12]:
def add_recipient_risk_features(df, delay=6, windows=[6, 12, 24]):
    
    df = df.sort_values(["step", "index"]).copy()
    
    result_list = []

    for recipient_id, group in df.groupby("recipient"):
        
        group = group.copy()
        
        # shift fraud labels to avoid leakage
        fraud_shifted = group["isFraud"].shift(delay)
        
        for window in windows:
            
            # Rolling over past N transactions
            fraud_count = fraud_shifted.rolling(window, min_periods=1).sum()
            tx_count = fraud_shifted.rolling(window, min_periods=1).count()
            
            # Risk = fraud ratio
            group[f"RECIP_RISK_{window}"] = fraud_count / (tx_count + 1e-8)
            group[f"RECIP_TX_COUNT_{window}"] = tx_count
        
        result_list.append(group)

    df = pd.concat(result_list)
    df = df.sort_values(["step", "index"]).reset_index(drop=True)
    df.fillna(0, inplace=True)
    
    return df

df_clean = add_recipient_risk_features(df_clean)

In [13]:
df_clean.head(10)

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,...,INIT_AMOUNT_DEV_TX_24,INIT_TX_COUNT_STEP_6,INIT_TX_COUNT_STEP_12,INIT_TX_COUNT_STEP_24,RECIP_RISK_6,RECIP_TX_COUNT_6,RECIP_RISK_12,RECIP_TX_COUNT_12,RECIP_RISK_24,RECIP_TX_COUNT_24
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,...,0.000,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0
1,0,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1,...,0.000,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0
2,0,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2,...,0.000,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,...,9650.580,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
4,0,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4,...,0.000,4,4,4,0.0,0.0,0.0,0.0,0.0,0.0
5,0,16973.75,4779013371563747,158601.88,141628.12,4593247015015219,54.33,17028.08,1,5,...,8213.430,4,4,4,0.0,0.0,0.0,0.0,0.0,0.0
6,0,659.02,4479448076398077,261950.48,261291.46,11-0003866,0.00,659.02,0,6,...,0.000,3,3,3,0.0,0.0,0.0,0.0,0.0,0.0
7,0,21103.99,4479448076398077,261291.46,240187.47,4649550475321678,19.63,21123.63,1,7,...,10222.485,3,3,3,0.0,0.0,0.0,0.0,0.0,0.0
8,0,648.89,4587942659105635,4808.94,4160.05,64-0008405,0.00,648.89,0,8,...,0.000,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
9,0,16908.07,4587942659105635,4160.05,4160.05,4863167876028593,66.12,66.12,1,9,...,8129.590,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
# drop_cols = [
#     "INIT_TX_COUNT_6", 
#     "INIT_TX_COUNT_12", 
#     "INIT_TX_COUNT_24",
#     "transactionType_DEBIT",
#     "transactionType_DEPOSIT",
#     "transactionType_PAYMENT",
#     "transactionType_WITHDRAWAL",
#     "neg_balance",
#     "INIT_AVG_AMOUNT_24",
#     "INIT_SUM_AMOUNT_24"
# ]

# df_clean = df_clean.drop(columns=drop_cols)
# df_clean.head()

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,...,INIT_AVG_AMOUNT_6,INIT_SUM_AMOUNT_6,INIT_AVG_AMOUNT_12,INIT_SUM_AMOUNT_12,RECIP_RISK_6,RECIP_TX_COUNT_6,RECIP_RISK_12,RECIP_TX_COUNT_12,RECIP_RISK_24,RECIP_TX_COUNT_24
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,...,19824.96,19824.96,19824.96,19824.96,0.0,0.0,0.0,0.0,0.0,0.0
1,0,598.97,4296267625767470,8.92,8.92,25-0000401,0.00,0.00,0,1,...,598.97,598.97,598.97,598.97,0.0,0.0,0.0,0.0,0.0,0.0
2,0,545.85,4178224023847746,93.60,-452.25,13-0001587,0.00,545.85,0,2,...,545.85,545.85,545.85,545.85,0.0,0.0,0.0,0.0,0.0,0.0
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,...,10196.43,20392.86,10196.43,20392.86,0.0,0.0,0.0,0.0,0.0,0.0
4,0,546.89,4779013371563747,159148.76,158601.88,75-0003564,0.00,546.89,0,4,...,546.89,546.89,546.89,546.89,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
save_directory = r"try_05"
os.makedirs(save_directory, exist_ok=True)

df_clean.to_pickle(os.path.join(save_directory , "featured_144days.pkl"))

In [15]:
df_fraud = df_clean[df_clean["isFraud"] == 1].copy()

print("Fraud dataset shape:", df_fraud.shape)
df_fraud.head(10)

Fraud dataset shape: (175518, 35)

,step,amount,initiator,oldBalInitiator,newBalInitiator,recipient,oldBalRecipient,newBalRecipient,isFraud,index,...,INIT_AMOUNT_DEV_TX_24,INIT_TX_COUNT_STEP_6,INIT_TX_COUNT_STEP_12,INIT_TX_COUNT_STEP_24,RECIP_RISK_6,RECIP_TX_COUNT_6,RECIP_RISK_12,RECIP_TX_COUNT_12,RECIP_RISK_24,RECIP_TX_COUNT_24
0,0,19824.96,4537027967639631,187712.18,167887.22,4875702729424478,8.31,19833.27,1,0,...,0.000,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0
3,0,19847.01,4178224023847746,-452.25,-20299.26,4096920916696293,4011.72,23858.74,1,3,...,9650.580,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
5,0,16973.75,4779013371563747,158601.88,141628.12,4593247015015219,54.33,17028.08,1,5,...,8213.430,4,4,4,0.0,0.0,0.0,0.0,0.0,0.0
7,0,21103.99,4479448076398077,261291.46,240187.47,4649550475321678,19.63,21123.63,1,7,...,10222.485,3,3,3,0.0,0.0,0.0,0.0,0.0,0.0
9,0,16908.07,4587942659105635,4160.05,4160.05,4863167876028593,66.12,66.12,1,9,...,8129.590,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
11,0,23715.64,4978866660478516,77826.87,54111.24,4822936618475944,14691.67,38407.31,1,11,...,11564.555,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
20,0,18533.84,4781213214714848,23562.49,5028.65,4663047917704976,68.34,18602.18,1,20,...,8977.565,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
25,0,21966.03,4120037473988300,318503.12,296537.08,4187906273321880,26.32,21992.36,1,25,...,10714.195,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
28,0,74145.41,4223078546024950,-632.85,-632.85,4840197438076267,11.96,11.96,1,28,...,36723.965,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0
30,0,23981.81,4799013284929379,19240.28,19240.28,4792446526809487,2020.97,2020.97,1,30,...,11692.810,2,2,2,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df_clean.columns

Index(['step', 'amount', 'initiator', 'oldBalInitiator', 'newBalInitiator',
       'recipient', 'oldBalRecipient', 'newBalRecipient', 'isFraud', 'index',
       'transactionType_DEBIT', 'transactionType_DEPOSIT',
       'transactionType_PAYMENT', 'transactionType_TRANSFER',
       'transactionType_WITHDRAWAL', 'amount_balance_ratio',
       'balance_increase_ratio', 'neg_balance_i', 'balance_error_i',
       'balance_error_r', 'INIT_AVG_AMOUNT_TX_6', 'INIT_AMOUNT_DEV_TX_6',
       'INIT_AVG_AMOUNT_TX_12', 'INIT_AMOUNT_DEV_TX_12',
       'INIT_AVG_AMOUNT_TX_24', 'INIT_AMOUNT_DEV_TX_24',
       'INIT_TX_COUNT_STEP_6', 'INIT_TX_COUNT_STEP_12',
       'INIT_TX_COUNT_STEP_24', 'RECIP_RISK_6', 'RECIP_TX_COUNT_6',
       'RECIP_RISK_12', 'RECIP_TX_COUNT_12', 'RECIP_RISK_24',
       'RECIP_TX_COUNT_24'],
      dtype='object')